# Site Settings
title: "Dornen.work"
email: "blank@blank.com"
description: "Technical blog. Mostly related to IT stuff"
baseurl: ""
url: "https://dornen.work"

theme: jekyll-theme-console
style: dark
header_pages:
  - index.md
  - about.md

footer: '[Telegram](https://t.me/dornendin), [Github](https://github.com/d-ornen)'

plugins:
  - jekyll-seo-tag