# Site Settings
title: "Dornen.work"
email: "blank@blank.com"
description: "Technical blog. Mostly related to IT stuff"
baseurl: ""
url: "https://dornen.work"

theme: jekyll-theme-console
style: dark
header_pages:
  - index.md
  - about.md
  - testing_features.md

footer: '<a href="https://t.me/dornendin">Telegram</a>, <a href="https://github.com/d-ornen">Github</a>'
plugins:
  - jekyll-seo-tag